markdown: redcarpet
redcarpet:
  extensions: []
pygments: true
permalink: /posts/:title
auto: true

name: Pavel Repin
url: http://pavel.repin.com
description: Remarks
twitter: pavelrepin
github: paxan
gravatar_url: http://www.gravatar.com/avatar/a0886310289840857f4763f2559b740c
